### ISSUE TITLE
Add pre-commit hook to detect API keys and secrets

### ISSUE THREAD

**Issue by aygp-dr** [aygp-dr/5dgai-intensive#3]
## Pre-commit Hook for API Keys and Secrets Detection

**Priority**: High  
**Type**: Security

### Overview

We need a pre-commit hook that scans commits for sensitive information like API keys, tokens, passwords, and other secrets that should never be committed to the repository.

### Requirements

1. **Detect Common Secret Patterns**:
   - API keys (Google AI Studio, OpenAI, Anthropic, etc.)
   - Authentication tokens
   - Passwords
   - Private keys
   - Access credentials

2. **Integration**:
   - Add to .pre-commit-config.yaml
   - Make setup easy for all contributors
   - Ensure it runs automatically before each commit

3. **User Experience**:
   - Clear error messages indicating what was detected
   - Instructions on how to fix the issue
   - Minimal false positives

### Implementation Options

1. Use [detect-secrets](https://github.com/Yelp/detect-secrets) for Python projects
2. Use [gitleaks](https://github.com/gitleaks/gitleaks) for broad coverage
3. Use [trufflehog](https://github.com/trufflesecurity/trufflehog) for comprehensive scanning

### Sample Configuration

```yaml
# .pre-commit-config.yaml
repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
```

### Follow-up Tasks

- [ ] Research and select the best tool for our needs
- [ ] Create baseline configuration 
- [ ] Add installation instructions to setup.org
- [ ] Test with sample secrets to ensure detection works
- [ ] Update CI/CD pipeline to also run checks
